### ISSUE TITLE
TypeError (superclass mismatch for class RetriableResponse)

### ISSUE THREAD

**Issue by fabioacd** [Flagsmith/flagsmith-ruby-client#30]
Hi, I'm trying to use flagsmith but when I call `Flagsmith::Client.new(....)` throws me the next error

> Traceback (most recent call last):
>        16: from (irb):8
>        15: from /bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
>        14: from /bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
>        13: from /bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
>        12: from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>        11: from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>        10: from /bundle/ruby/2.7.0/gems/flagsmith-3.1.1/lib/flagsmith.rb:4:in `<top (required)>'
>         9: from /bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
>         8: from /bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
>         7: from /bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
>         6: from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         5: from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         4: from /bundle/ruby/2.7.0/gems/faraday-retry-1.0.3/lib/faraday/retry.rb:3:in `<top (required)>'
>         3: from /bundle/ruby/2.7.0/gems/faraday-retry-1.0.3/lib/faraday/retry.rb:3:in `require_relative'
>         2: from /bundle/ruby/2.7.0/gems/faraday-retry-1.0.3/lib/faraday/retriable_response.rb:4:in `<top (required)>'
>         1: from /bundle/ruby/2.7.0/gems/faraday-retry-1.0.3/lib/faraday/retriable_response.rb:6:in `<module:Faraday>'
> TypeError (superclass mismatch for class RetriableResponse)

Any thoughts? Thank you in advance for your help

**Comment by dabeeeenster** [comment]
Hi, we will investigate this issue and get back to you as soon as we have an update. In the meantime, we will really appreciate it if you could provide any additional information that could help us to reproduce the issue. For example the Stack and environment configuration, mainly the Operating System, and if you are running the self-hosted version. Thanks in advance!

**Comment by fabioacd** [comment]
Hey @dabeeeenster  sure,
OS: Ubuntu 20.04.5 LTS
Ruby: ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux-musl]

**Comment by matthewelwell** [comment]
@fabioacd can you confirm the version of the flagsmith ruby SDK you are using as well please?

**Comment by fabioacd** [comment]
Hey @matthewelwell  sure!
After the bundle for `gem install 'flagsmith'` this is how the Gemfile.lock looks like

> faraday-retry (1.0.3)
> faraday_middleware (0.14.0)
>   faraday (>= 0.7.4, < 1.0)
> ffi (1.15.5)
> flagsmith (3.1.1)
>   faraday
>   faraday-retry
>   faraday_middleware
>   semantic

**Comment by matthewelwell** [comment]
Hi @fabioacd, I'm not able to reproduce this with a basic setup using ruby 2.7.8. I'd hazard a guess that the issue is with the fact that you're pinning `faraday` to `< 1.0`. If I run the exact following commands in a clean project dir using ruby 2.7, I end up with the Gemfile.lock also provided below. 

```bash
bundle init
bundle add flagsmith
```

```
# Gemfile.lock

GEM
  remote: https://rubygems.org/
  specs:
    faraday (1.10.3)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    flagsmith (3.1.1)
      faraday
      faraday-retry
      faraday_middleware
      semantic
    multipart-post (2.3.0)
    ruby2_keywords (0.0.5)
    semantic (1.6.1)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  flagsmith (~> 3.1)

BUNDLED WITH
   2.3.14
```

Can you verify if you still see this issue in a clean project in your environment? If not, please can you verify if one of your other dependencies is pinning faraday to `<1.0` ?

**Comment by matthewelwell** [comment]
... and the script I used to verify the issue was not present: 

```ruby
require "flagsmith"

$flagsmith = Flagsmith::Client.new(
  environment_key: '<KEY>'
)

$flags = $flagsmith.get_environment_flags()

puts $flags.get_feature_value('my_flag')
```

**Comment by zachaysan** [comment]
I was able to reproduce this issue, and I verified what Matt was suggesting that it was an issue in versioning `faraday`. I'm putting together a small version limiting to prevent this issue for others in the future. The earliest `faraday` gem that can be used without a collision is `1.0.0` which is almost 4 years old.

**Comment by zachaysan** [comment]
The relevant PR is here:

https://github.com/Flagsmith/flagsmith-ruby-client/pull/37
