### ISSUE TITLE
v4 Dependency Issues

### ISSUE THREAD

**Issue by thiemok** [Flagsmith/flagsmith-ruby-client#44]
Hello! I'm struggling to use version 4 of this gem.
I'm somewhat newish to ruby so please excuse me if I missed something.

I've added the gem to my application using `bundle add flagsmith`.
Afterwards the application fails to launch because the gem `pry` can't be found.

Looking the [gemspec](https://github.com/Flagsmith/flagsmith-ruby-client/blob/main/flagsmith.gemspec#L29-L30) it seems that `pry` and `pry-byebug` are only defined as a dev dependency and thus should not be required.
However both gems are required in a way that seems like they are not optional by [lib/flagsmith.rb](https://github.com/Flagsmith/flagsmith-ruby-client/blob/main/lib/flagsmith.rb#L3-L4)

**Comment by dabeeeenster** [comment]
Please can you raise an issue in the repo?

**Comment by zachaysan** [comment]
Thanks for bringing to my attention @thiemok this was my error. I'll update the gem soon though it may not be published quickly. In the mean time can you use `v3.2.0`?

**Comment by thiemok** [comment]
> In the mean time can you use v3.2.0?

I briefly looked into using that version, but ran into some gem version conflict with `faraday` and didn't pursue it further.
I believe if I have to I can run the patched v4 for off of a forked git repo.

**Comment by zachaysan** [comment]
I've opened a PR for the dev dependency fix here:

https://github.com/Flagsmith/flagsmith-ruby-client/pull/45

Typically we upgrade versions in their own PR once other PRs have been reviewed and merged. The other lead ruby developers at Flagsmith are both unavailable for a couple days so there may be some delay in getting this merged in.

**Comment by zachaysan** [comment]
Hey @thiemok I was able to get the PRs reviewed and I cut a new gem that you should be able to use:

https://rubygems.org/gems/flagsmith/versions/4.0.1

Let me know if you have any other issues. I'm going to close this PR as complete.
