### ISSUE TITLE
get_flags does not return segments

### ISSUE THREAD

**Issue by wasabigeek** [Flagsmith/flagsmith-ruby-client#5]
Hi, the source seems to suggest that when listing all flags, the respective `segments` will be returned as well  https://github.com/BulletTrainHQ/bullet-train-ruby-client/blob/master/lib/bullet_train.rb#L26

In practice, it doesn't seem to be the case, is that expected? This is our setup:
![image](https://user-images.githubusercontent.com/4256705/97290965-3e9a9580-1884-11eb-9ee0-6b950b0c589c.png)

And this is the partial response for `get_flags`, where segment is `nil`:
```
...
"test_segments" => {
        :enabled => false,
          :value => nil,
        :segment => nil
    }
...
```

**Comment by dabeeeenster** [comment]
Hi,

This is a bug - we never return segments! They are used to drive flags. I'll add an issue. Thanks for the report!
