### ISSUE TITLE
Calls to environment_data_polling_manager cause unintended network requests

### ISSUE THREAD

**Issue by thijsnado** [Flagsmith/flagsmith-ruby-client#56]
We wanted to call `client.environment_data_polling_manager.stop` manually in our code to prevent networking requests during tests. Doing this though causes networking requests do to the line at https://github.com/Flagsmith/flagsmith-ruby-client/blob/main/lib/flagsmith.rb#L106. This seems to make sense for initial calls to `environment_data_polling_manager` but I would expect subsequent calls to environment_data_polling_manager to return the initialized manager.

**Comment by zachaysan** [comment]
I think I'm following what you're saying. Sort of do a `@environment_data_polling_manager.nil?` check and avoid the update environment call if one is present, right? 

Would you like to create a PR for the fix?
