### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by NeoPhi** [Flagsmith/flagsmith-ruby-client#6]
Are there plans to publish a version of the gem with the new name?

**Comment by dabeeeenster** [comment]
There are but we're prioritising other features right now - happy to take a PR tho!

**Comment by NeoPhi** [comment]
Let me know what you think about https://github.com/Flagsmith/flagsmith-ruby-client/pull/7

**Comment by dabeeeenster** [comment]
Thanks so much @NeoPhi  - this is really great. Will push to a new ruby gem now.
